# Generated by Django 2.2 on 2023-03-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subject', models.IntegerField(choices=[(1, '화면구현'), (2, '구현'), (3, '응용'), (4, '영어'), (5, '분석'), (6, '논술'), (7, '수학'), (8, '국어')], default=None)),
                ('content', models.TextField()),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
