# Generated by Django 2.2 on 2023-03-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20230327_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='subject',
            field=models.CharField(choices=[('화면구현', '화면구현'), ('구현', '구현'), ('응용', '응용'), ('영어', '영어'), ('분석', '분석'), ('논술', '논술'), ('수학', '수학'), ('국어', '국어')], default=None, max_length=4),
        ),
    ]
